name: test-workflow
on:
        push:
                branches:
                        - dev-0.1
jobs:
        echo-test:
                runs-on: windows-latest
                steps:
                        - runs: echo "Hello World"
                        - runs: dir
